[package]
name = "mayda_macros"
version = "0.1.0"
authors = ["Jeremy Mason <jkylemason@gmail.com>"]
license = "MIT"
description = "Macros to generate basic encoding and decoding functions used by mayda"
repository = "https://github.com/harharkh/mayda"
documentation = "https://harharkh.github.io/mayda"
keywords = ["mayda", "compression"]

[lib]
name = "mayda_macros"
plugin = true
