[package]
name = "mayda"
version = "0.0.1"
authors = ["Jeremy Mason <jkylemason@gmail.com>"]

[lib]
name = "mayda"

[dependencies]
mayda_codec = { path = "mayda_codec", version = "0.0.1" }
rand = "0.3"
